"""Make mgmt_no nullable and clear auto-generated values

Revision ID: 001
Revises:
Create Date: 2026-06-28
"""
from alembic import op
import sqlalchemy as sa

revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Allow NULL in mgmt_no column (batch mode supports both SQLite and PostgreSQL)
    with op.batch_alter_table("misu_members", schema=None) as batch_op:
        batch_op.alter_column(
            "mgmt_no",
            existing_type=sa.String(16),
            nullable=True,
            existing_nullable=False,
        )

    # 2. Clear "관리번호미상-XXX" — always auto-generated by imports.py fallback
    op.execute(
        "UPDATE misu_members SET mgmt_no = NULL WHERE mgmt_no LIKE '관리번호미상-%'"
    )

    # 3. Clear 신YY-NNN values that were auto-assigned by _next_mgmt_no() during
    #    pending→member promotion (pending record had no real mgmt_no at promotion time)
    op.execute(
        """
        UPDATE misu_members SET mgmt_no = NULL
        WHERE id IN (
            SELECT promoted_member_id
            FROM misu_pending
            WHERE promoted_member_id IS NOT NULL
              AND (mgmt_no IS NULL OR mgmt_no = '')
        )
        AND mgmt_no LIKE '신__-%'
        """
    )


def downgrade() -> None:
    # Cannot restore auto-generated values — downgrade is a no-op
    pass
