import React, { useMemo, useState } from 'react'
import { Card, PageHead, Badge, formatWon } from '../components.jsx'

export default function ClosureBoard({data, updateClosure, restoreClosure, deleteClosure}){
  const [q,setQ]=useState(''); const [edit,setEdit]=useState(null)
  const rows=useMemo(()=>data.closures.filter(c=>!q||[c.name,c.vehicleNo,c.docNo,c.content,c.type].join(' ').includes(q)),[data.closures,q])
  const total=rows.length; const unpaid=rows.reduce((s,c)=>s+(Number(c.unpaidBalance)||0),0); const notify=rows.filter(c=>c.notifyLater).length
  return <div><PageHead title="폐업현황" desc="폐업·탈퇴·양도·이관 처리 이력과 추후 납부 안내 대상을 확인합니다."/>
    <div className="grid grid-4" style={{marginBottom:14}}><Card className="stat"><div className="stat-label">전체 처리 건</div><div className="stat-value">{total}</div></Card><Card className="stat"><div className="stat-label">추후 납부 안내</div><div className="stat-value" style={{color:'var(--orange)'}}>{notify}건</div></Card><Card className="stat"><div className="stat-label">미납 잔액 합계</div><div className="stat-value" style={{color:'var(--red)'}}>{formatWon(unpaid)}</div></Card><Card className="stat"><div className="stat-label">복귀/삭제</div><div className="stat-note">오처리 시 복귀 가능</div></Card></div>
    <Card className="card-pad" style={{marginBottom:14}}><div className="filters"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="이름 / 차량번호 / 관리번호·접수번호 / 내용 검색"/></div></Card>
    <Card><div className="table-wrap"><table className="table"><thead><tr><th>처리일</th><th>지역</th><th>이름</th><th>차량번호</th><th>사유</th><th>관리번호/접수번호</th><th>내용</th><th className="right">미납잔액</th><th>추후 연락</th><th className="right">처리</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td>{c.processDate}</td><td>{c.sigun}</td><td><b>{c.name}</b></td><td className="mono">{c.vehicleNo}</td><td><Badge tone="red">{c.type}</Badge></td><td>{c.docNo||'-'}</td><td className="ellipsis">{c.content}</td><td className="right money">{formatWon(c.unpaidBalance)}</td><td>{c.notifyLater?<Badge tone="orange">납부 안내</Badge>:<Badge tone="green">종결</Badge>}</td><td className="right action-cell"><button className="btn soft" onClick={()=>alert(`상세\n${c.name} / ${c.vehicleNo}\n${c.content || ''}`)}>상세</button><button className="btn" onClick={()=>setEdit(c)}>수정</button><button className="btn green" onClick={()=>{if(confirm('정상 회원으로 복귀하고 폐업현황 기록을 제거할까요?')) restoreClosure(c.id)}}>복귀</button><button className="btn red" onClick={()=>{if(confirm('폐업/이탈 처리 기록을 삭제합니다. 회원 상태 복구 여부를 확인하세요. 계속하시겠습니까?')) deleteClosure(c.id,false)}}>삭제</button></td></tr>)}{!rows.length&&<tr><td colSpan="10" style={{textAlign:'center',padding:32,color:'var(--sub)'}}>폐업/이탈 처리 내역이 없습니다.</td></tr>}</tbody></table></div></Card>
    {edit&&<ClosureEditModal item={edit} onClose={()=>setEdit(null)} onSave={(payload)=>{updateClosure(edit.id,payload); setEdit(null)}}/>}
  </div>
}

function ClosureEditModal({item,onClose,onSave}){const [type,setType]=useState(item.type||'폐업'); const [docNo,setDocNo]=useState(item.docNo||''); const [content,setContent]=useState(item.content||''); const [unpaid,setUnpaid]=useState(item.unpaidBalance||0); const [notify,setNotify]=useState(!!item.notifyLater); return <div className="modal-bg"><div className="modal"><h3>폐업/이탈 기록 수정</h3><div className="form-row"><b>처리사유</b><select className="select" value={type} onChange={e=>setType(e.target.value)}><option>폐업</option><option>탈퇴</option><option>양도</option><option>이관</option></select></div><div className="form-row"><b>관리번호/접수번호</b><input className="input" value={docNo} onChange={e=>setDocNo(e.target.value)}/></div><div className="form-row"><b>미납잔액</b><input className="input" type="number" value={unpaid} onChange={e=>setUnpaid(e.target.value)}/></div><div className="form-row"><b>추후 안내</b><select className="select" value={notify?'예':'아니오'} onChange={e=>setNotify(e.target.value==='예')}><option>예</option><option>아니오</option></select></div><div className="form-row"><b>내용</b><textarea className="textarea" value={content} onChange={e=>setContent(e.target.value)}/></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button className="btn" onClick={onClose}>취소</button><button className="btn primary" onClick={()=>onSave({type, doc_no:docNo, content, unpaid_balance:Number(unpaid)||0, notify_later:notify})}>저장</button></div></div></div>}
